.TH DWM 1 dwm-0.0
.SH NAME
dwm \- dynamic window manager
.SH SYNOPSIS
.B dwm
.RB [ \-v ]
.SH DESCRIPTION
.SS Overview
.B dwm
is a dynamic window manager for X11.
.SS Options
.TP
.B \-v
prints version information to stdout, then exits.
.SS Default Key Bindings
.TP 16
.I Key	
.I Action
.TP
.B Mod1-Return
Zoom
.B window
to the 
.B master
track
.TP
.B Mod1-k
Focus previous
.B window
.TP
.B Mod1-j
Focus next
.B window
.TP
.B Mod1-m
Maximize current
.B window
.TP
.B Mod1-[0..n]
Focus
.B nth
tag
.TP
.B Mod1-space
(Re-)arrange
.B all
windows tiled
